version: '3.8'

services:
  postgres:
    build: .
    # Или используйте готовый образ: image: postgres:15
    container_name: todoapp_postgres
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: